application: arunshankerprasad
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: main.app
